name: Rust CI

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
